title: 拾光集
description: 写代码，也写生活
author: 林一
email: hello@example.com
lang: zh-CN
timezone: Asia/Shanghai

baseurl: "/blog"
url: "https://w-joslin-x.github.io"

markdown: kramdown
highlighter: rouge
permalink: /articles/:year/:month/:day/:title/

collections:
  essays:
    output: true
    permalink: /articles/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "essays"
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
